### ISSUE TITLE
Error while loading pretrained weights

### ISSUE THREAD

**Issue by trancenoid** [wuhuikai/GP-GAN#19]
I got the following error while loading the blending_GAN.npz for resuming the training. I want to fine tune the data on a different dataset. Its training on it from scratch but cannot load the provided weights
```
Traceback (most recent call last):
  File "train_blending_gan.py", line 178, in <module>
    main()
  File "train_blending_gan.py", line 170, in main
    chainer.serializers.load_npz(args.resume, trainer)
  File "/usr/local/lib/python3.6/dist-packages/chainer/serializers/npz.py", line 243, in load_npz
    d.load(obj)
  File "/usr/local/lib/python3.6/dist-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/trainer.py", line 388, in serialize
    self.updater.serialize(serializer['updater'])
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/updaters/standard_updater.py", line 265, in serialize
    iterator.serialize(serializer['iterator:' + name])
  File "/usr/local/lib/python3.6/dist-packages/chainer/iterators/multiprocess_iterator.py", line 218, in serialize
    self.current_position)
  File "/usr/local/lib/python3.6/dist-packages/chainer/serializers/npz.py", line 176, in __call__
    dataset = self.npz[key]
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'updater/iterator:main/current_position is not a file in the archive'
```
Note : The weight file was renamed for convenience, the path is correct.

**Comment by wuhuikai** [comment]
1. Do you unzip the file?
2. What's the version of your chainer?

**Comment by eman-rezk** [comment]
I got the same error while resuming the training, I'm using chainer 6.3.0. I use the resume parameter and give it the path of the blending_GAN.npz.

**Comment by wuhuikai** [comment]
This project uses a very old version of chainer, try `chainer==1.xx.0` : )

**Comment by eman-rezk** [comment]
I changed the chainer to 1.0, but get the same error

**Comment by eman-rezk** [comment]
Traceback (most recent call last):
  File "train_blending_gan.py", line 213, in <module>
    main()
  File "train_blending_gan.py", line 205, in main
    chainer.serializers.load_npz(args.resume, trainer)
  File "/usr/local/lib/python3.6/dist-packages/chainer/serializers/npz.py", line 242, in load_npz
    d.load(obj)
  File "/usr/local/lib/python3.6/dist-packages/chainer/serializer.py", line 83, in load
    obj.serialize(self)
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/trainer.py", line 361, in serialize
    self.updater.serialize(serializer['updater'])
  File "/usr/local/lib/python3.6/dist-packages/chainer/training/updaters/standard_updater.py", line 199, in serialize
    iterator.serialize(serializer['iterator:' + name])
  File "/usr/local/lib/python3.6/dist-packages/chainer/iterators/multiprocess_iterator.py", line 216, in serialize
    self.current_position)
  File "/usr/local/lib/python3.6/dist-packages/chainer/serializers/npz.py", line 175, in __call__
    dataset = self.npz[key]
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 266, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'updater/iterator:main/current_position is not a file in the archive'

**Comment by wuhuikai** [comment]
can you use it for testing?

**Comment by eman-rezk** [comment]
yes, it is working fine for testing

**Comment by wuhuikai** [comment]
I see, the npz file only contains params of G, thus can not be used for finetuning : (
