### ISSUE TITLE
ValueError: axes don't match array

### ISSUE THREAD

**Issue by aradhyamathur** [wuhuikai/GP-GAN#5]
Upon selecting 2 images of the same size I run into this error for the run_gp_gan.py. Can someone guide. What could be the possible error I am committing?

**Comment by wuhuikai** [comment]
Can you upload the full error message?

**Comment by shubham0704** [comment]
Full error message - 
```
python run_gp_gan.py --src_image images/test_images/src.jpg --dst_image images/test_images/dst.jpg --mask_image images/test_images/mask_display.png --blended_image images/test_images/result.png
Input arguments:
	ngf: 64
	src_image: images/test_images/src.jpg
	nc: 3
	g_path: models/blending_gan.npz
	image_size: 64
	sigma: 0.5
	mask_image: images/test_images/mask_display.png
	list_path: 
	gpu: 0
	nz: 100
	unsupervised_path: models/unsupervised_blending_gan.npz
	smooth_sigma: 1
	nBottleneck: 4000
	color_weight: 1
	supervised: True
	gradient_kernel: normal
	nef: 64
	result_folder: blending_result
	blended_image: images/test_images/result.png
	dst_image: images/test_images/dst.jpg
	n_iteration: 1000
	ndf: 64

Load pretrained Blending GAN model from models/blending_gan.npz ...
Processing 1/1 ...
Traceback (most recent call last):
  File "run_gp_gan.py", line 107, in <module>
    main()
  File "run_gp_gan.py", line 99, in main
    nz=args.nz, n_iteration=args.n_iteration)
  File "/home/master/Documents/COE/GP-GAN/gp_gan.py", line 187, in gp_gan
    copy_paste_init_var = Variable(chainer.dataset.concat_examples([preprocess(copy_paste_init)], gpu))
  File "/home/master/Documents/COE/GP-GAN/gp_gan.py", line 30, in preprocess
    im = np.transpose(im*2-1, (2, 0, 1)).astype(np.float32)
  File "/home/master/anaconda3/envs/gpgan/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/master/anaconda3/envs/gpgan/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
```

**Comment by shubham0704** [comment]
Btw, I ported the code to chainer 2.0 to make it work with anaconda. 
So the code works with a mask which is totally dark i.e test_images/mask.png but it doesn't work with test_images/mask_display.png.
Changes -
remove ```test=``` global configuration from model.py, gp_gan.py and added ```with chainer.using_config(test, args.supervised)``` in run_gp_gan.py. Haven't touched other files. My fair guess is that these minor changes do not affect this issue

**Comment by wuhuikai** [comment]
`test_images/mask_display.png`  should not be used as the mask image.
`test_images/mask.png` is the right mask image, which is not a dark image at all.
The pixel value in it is `0` or `1`.

**Comment by shubham0704** [comment]
Got it. Thanks for clarifying :)
